name: Schedule Test Pipeline

on:
  schedule:
    - cron: "10 10 * * *"   # Runs daily at 3:05 PM IST

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print test message
        run: echo "Scheduled pipeline executed at $(date -u) UTC"

