name: Schedule Test Pipeline

on:
  schedule:
    - cron: "17 15 * * *"   # Runs daily at 3:05 PM IST
  workflow_dispatch:        # Allows manual testing

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print test message
        run: echo "Scheduled pipeline executed at $(date -u) UTC"

